import { z } from 'astro/zod';
export const YOUTUBE_CHANNEL_URL = 'https://www.youtube.com/@%E6%9C%AC%E6%97%A5%E6%9C%89%E6%93%9A%E5%BD%B1%E9%9F%B3/shorts';
export const videoItemSchema = z.object({ id: z.string().min(1), title: z.string().min(1), publishedAt: z.string().optional(), updatedAt: z.string().optional(), youtubeUrl: z.string().url(), shortsUrl: z.string().regex(/^https:\/\/www\.youtube\.com\/shorts\/[A-Za-z0-9_-]+$/), embedUrl: z.string().regex(/^https:\/\/www\.youtube\.com\/embed\/[A-Za-z0-9_-]+$/), thumbnailUrl: z.string().url().optional(), source: z.enum(['youtube-rss', 'youtube-api', 'fallback']) });
export type VideoItem = z.infer<typeof videoItemSchema>; export const videoItemsSchema = z.array(videoItemSchema);
const decodeXml=(s:string)=>s.replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"').replaceAll('&#39;',"'");
const mk=(id:string,title:string,publishedAt?:string,updatedAt?:string,source:VideoItem['source']='youtube-rss'):VideoItem=>({id,title,publishedAt,updatedAt,youtubeUrl:`https://www.youtube.com/watch?v=${id}`,shortsUrl:`https://www.youtube.com/shorts/${id}`,embedUrl:`https://www.youtube.com/embed/${id}`,thumbnailUrl:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,source});
export const sortAndDedupe=(items:VideoItem[])=>[...new Map(items.map(i=>[i.id,i])).values()].sort((a,b)=>new Date(b.publishedAt??b.updatedAt??0).getTime()-new Date(a.publishedAt??a.updatedAt??0).getTime());
export async function fetchFromRss(channelId:string){const r=await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`);if(!r.ok) throw new Error(`RSS failed: ${r.status}`);const xml=await r.text();const entries=[...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(m=>m[1]);return entries.map(e=>{const id=e.match(/<yt:videoId>([^<]+)<\/yt:videoId>/)?.[1];const t=e.match(/<title>([\s\S]*?)<\/title>/)?.[1];if(!id||!t)return null;return mk(id,decodeXml(t.trim()),e.match(/<published>([^<]+)<\/published>/)?.[1],e.match(/<updated>([^<]+)<\/updated>/)?.[1],'youtube-rss')}).filter(Boolean) as VideoItem[];}
export async function fetchFromApi(channelId:string,apiKey:string,uploadsPlaylistId?:string){let p=uploadsPlaylistId;if(!p){const u=new URL('https://www.googleapis.com/youtube/v3/channels');u.searchParams.set('part','contentDetails');u.searchParams.set('id',channelId);u.searchParams.set('key',apiKey);const cr=await fetch(u);if(!cr.ok) throw new Error(`channels.list failed: ${cr.status}`);const cd=await cr.json() as any;p=cd?.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;}if(!p) throw new Error('uploads playlist missing');const u=new URL('https://www.googleapis.com/youtube/v3/playlistItems');u.searchParams.set('part','snippet,contentDetails');u.searchParams.set('playlistId',p);u.searchParams.set('maxResults','50');u.searchParams.set('key',apiKey);const r=await fetch(u);if(!r.ok) throw new Error(`playlistItems.list failed: ${r.status}`);const d=await r.json() as any;return (d?.items??[]).map((i:any)=>{const id=i?.contentDetails?.videoId;const t=i?.snippet?.title;if(!id||!t)return null;return mk(id,t,i?.contentDetails?.videoPublishedAt,i?.snippet?.publishedAt,'youtube-api')}).filter(Boolean) as VideoItem[];}
